"""create table naturalGasEodValue

Revision ID: 420d504679d7
Revises: f2022b579625
Create Date: 2025-04-15 18:04:37.093659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420d504679d7'
down_revision: Union[str, None] = 'f2022b579625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naturalGasEodValue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naturalGasEodValue_date'), 'naturalGasEodValue', ['date'], unique=False)
    op.create_index(op.f('ix_naturalGasEodValue_id'), 'naturalGasEodValue', ['id'], unique=True)
    op.create_index(op.f('ix_naturalGasEodValue_tag'), 'naturalGasEodValue', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_naturalGasEodValue_tag'), table_name='naturalGasEodValue')
    op.drop_index(op.f('ix_naturalGasEodValue_id'), table_name='naturalGasEodValue')
    op.drop_index(op.f('ix_naturalGasEodValue_date'), table_name='naturalGasEodValue')
    op.drop_table('naturalGasEodValue')
    # ### end Alembic commands ###
