"""create table PeakDay

Revision ID: 4e6a645097dd
Revises: 017a249b5fb6
Create Date: 2025-04-13 16:55:43.582771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6a645097dd'
down_revision: Union[str, None] = '017a249b5fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricPeakDay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('peak_date', sa.Date(), nullable=False),
    sa.Column('peak_datetime', sa.DateTime(), nullable=False),
    sa.Column('peak_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricPeakDay_id'), 'electricPeakDay', ['id'], unique=False)
    op.create_index(op.f('ix_electricPeakDay_peak_date'), 'electricPeakDay', ['peak_date'], unique=False)
    op.create_index(op.f('ix_electricPeakDay_peak_datetime'), 'electricPeakDay', ['peak_datetime'], unique=False)
    op.create_index(op.f('ix_electricPeakDay_peak_type'), 'electricPeakDay', ['peak_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_electricPeakDay_peak_type'), table_name='electricPeakDay')
    op.drop_index(op.f('ix_electricPeakDay_peak_datetime'), table_name='electricPeakDay')
    op.drop_index(op.f('ix_electricPeakDay_peak_date'), table_name='electricPeakDay')
    op.drop_index(op.f('ix_electricPeakDay_id'), table_name='electricPeakDay')
    op.drop_table('electricPeakDay')
    # ### end Alembic commands ###
