"""create table naturalGasTanktable

Revision ID: f2022b579625
Revises: 4e6a645097dd
Create Date: 2025-04-15 15:34:05.809960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2022b579625'
down_revision: Union[str, None] = '4e6a645097dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naturalGasTanktable',
    sa.Column('level_cm', sa.Integer(), nullable=False),
    sa.Column('lmpt2_tank1_m3', sa.Float(), nullable=True),
    sa.Column('lmpt2_tank2_m3', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('level_cm')
    )
    op.create_index(op.f('ix_naturalGasTanktable_level_cm'), 'naturalGasTanktable', ['level_cm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_naturalGasTanktable_level_cm'), table_name='naturalGasTanktable')
    op.drop_table('naturalGasTanktable')
    # ### end Alembic commands ###
